(async()=>{const checks=[];const pause=()=>new Promise(r=>setTimeout(r,350));const check=(name,condition)=>{checks.push({name,pass:!!condition});if(!condition)throw Error(name);};const set=(path,value)=>{const el=document.querySelector('[data-inst="'+path+'"]');if(!el)throw Error('Missing '+path);if(el.type==='checkbox')el.checked=value;else el.value=value;el.dispatchEvent(new Event(el.tagName==='SELECT'||el.type==='checkbox'?'change':'input',{bubbles:true}));};const nav=async route=>{location.hash=route;await pause();};const U=await import('./underwriting-ui.js');const before=U.institutionSnapshot();
check('Decision matrix and three scenarios rendered',document.querySelectorAll('.decision-table thead th').length===4);
set('equipmentDeal.proposedCapFinancingPct',.5);check('Input recalculates proposed debt',U.institutionSnapshot().equipmentDeal.proposedCapFinancingPct===.5&&document.querySelector('.decision-table').textContent.includes('Rp15,000,000,000'));
set('equipmentDeal.proposedCapFinancingPct',1.2);check('Invalid input retains prior valid state',U.institutionSnapshot().equipmentDeal.proposedCapFinancingPct===.5&&document.querySelector('#institution-error').textContent.includes('retained'));
set('equipmentDeal.proposedCapFinancingPct',before.equipmentDeal.proposedCapFinancingPct);
set('equipmentDeal.repaymentStructure','ANNUITY');set('equipmentDeal.gracePeriodMonths',3);check('Annuity and grace accepted',U.institutionSnapshot().equipmentDeal.gracePeriodMonths===3);
set('equipmentDeal.repaymentStructure',before.equipmentDeal.repaymentStructure);set('equipmentDeal.gracePeriodMonths',0);
document.querySelector('[data-inst-audit="PROPOSED_CAP:year1"]').click();check('DSCR audit displays populated inputs',document.querySelector('#modal').textContent.includes('6,081,666,666'));document.querySelector('#close-modal').click();
await nav('spread');check('Financial spread and ICR rendered',document.body.textContent.includes('EBIT / interest'));document.querySelector('[data-inst-haircut="0"]').click();check('Audit sensitivity applied explicitly',U.institutionSnapshot().financialSpreading.years[0].auditQualityHaircutPct===.2);document.querySelector('[data-inst-action="common-size"]').click();check('Common-size table rendered',document.body.textContent.includes('Balance metric / total assets'));document.querySelector('[data-inst-action="common-size"]').click();
await nav('recon');check('Adjusted bank turnover rendered',document.body.textContent.includes('Rp27,600,000,000'));set('bankReconciliation.statements.0.bouncedChecksCount',1);check('Bank exception recalculates',document.body.textContent.includes('rejected / bounced'));set('bankReconciliation.statements.0.bouncedChecksCount',0);
await nav('governance');set('groupExposure.bankLegalLendingLimitBMPK',1e9);check('Critical group breach visible',!document.querySelector('#institution-ceiling').hidden);set('groupExposure.bankLegalLendingLimitBMPK',before.groupExposure.bankLegalLendingLimitBMPK);
await nav('proposal');set('memo.analyst','Browser QA Analyst');set('memo.rationale','Verify the repayment capacity and contract evidence.');check('Memo editor populates proposal',document.querySelector('.institutional-proposal').textContent.includes('Browser QA Analyst'));
await pause();check('Autosave contains edited memo',JSON.parse(localStorage.getItem('credit-institution-v2')).memo.analyst==='Browser QA Analyst');set('memo.analyst',before.memo.analyst);set('memo.rationale',before.memo.rationale);await pause();window.__creditQA=checks;return checks;})()
